Transform: AWS::Serverless-2016-10-31

Parameters:
  Product:
    Description: Product name
    Type: String

  Environment:
    Description: An environment name that will be prefixed to resource names
    Type: String

Globals:
  Function:
    Runtime: ruby2.5
    Timeout: 10
    Environment:
      Variables:
        S3_BUCKET: !Ref S3Bucket

Resources:
  DocumentRendererLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 'app/document_renderer/'
      Handler: lambda.DocumentRenderer::Lambda.handler
      Environment:
        Variables:
          EVENT_SOURCE_SQS_URL: !Ref RenderingSQSQueue
          PDF_GENERATION_SQS_URL: !Ref PDFGenerationSQSQueue
          EVENT_DEST_SNS_TOPIC: !Ref DocumentsSNSTopic
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RenderingSQSQueue.Arn
            BatchSize: 10
      Layers:
        - !Ref DocumentRendererRubyGemsLayer
        - !Ref CommonRubyGemsLayer
        - !Ref LibLayer
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
        - SQSPollerPolicy:
            QueueName: !GetAtt RenderingSQSQueue.QueueName
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt DocumentsSNSTopic.TopicName

  DocumentRendererRubyGemsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: document_renderer
      ContentUri: .layers/document_renderer/
      CompatibleRuntimes:
        - ruby2.5
      RetentionPolicy: Delete

  PDFGeneratorLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 'app/pdf_generator/'
      Handler: lambda.PDFGenerator::Lambda.handler
      Environment:
        Variables:
          EVENT_SOURCE_SQS_URL: !Ref PDFGenerationSQSQueue
          EVENT_DEST_SNS_TOPIC: !Ref DocumentsSNSTopic
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt PDFGenerationSQSQueue.Arn
            BatchSize: 1
      MemorySize: 512
      Layers:
        - arn:aws:lambda:ap-southeast-2:764866452798:layer:libreoffice:1
        - !Ref PDFGeneratorRubyGemsLayer
        - !Ref CommonRubyGemsLayer
        - !Ref LibLayer
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
        - SQSPollerPolicy:
            QueueName: !GetAtt PDFGenerationSQSQueue.QueueName
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt DocumentsSNSTopic.TopicName

  PDFGeneratorRubyGemsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pdf_generator
      ContentUri: .layers/pdf_generator/
      CompatibleRuntimes:
        - ruby2.5
      RetentionPolicy: Delete

  CommonRubyGemsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common_gems
      ContentUri: .layers/common/
      CompatibleRuntimes:
        - ruby2.5
      RetentionPolicy: Delete

  LibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lib
      ContentUri: .layers/lib/
      CompatibleRuntimes:
        - ruby2.5
      RetentionPolicy: Delete

  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub "${Product}-${Environment}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          -
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          -
            ExpirationInDays: 14
            Status: Enabled

  S3BucketSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description : "S3 Bucket"
      Name: !Sub "/${Product}/${Environment}/S3_BUCKET"
      Type: String
      Value: !Ref S3Bucket

  DocumentsSNSTopic:
    Type: AWS::SNS::Topic

  RenderingSQSQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt RenderingSQSDeadLetterQueue.Arn
        maxReceiveCount: 3

  RenderingSQSDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600

  PDFGenerationSQSQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PDFGenerationSQSDeadLetterQueue.Arn
        maxReceiveCount: 3

  PDFGenerationSQSDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600

  DocumentsSNSTopicSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description : "Documents SNS Topic"
      Name: !Sub "/${Product}/${Environment}/DOCUMENTS_SNS_TOPIC"
      Type: String
      Value: !Ref DocumentsSNSTopic

  RenderingSQSQueueSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description : "Rendering SQS Queue"
      Name: !Sub "/${Product}/${Environment}/RENDERING_SQS_QUEUE"
      Type: String
      Value: !Ref RenderingSQSQueue

  PDFGenerationSQSQueueSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description : "PDF generation SQS Queue"
      Name: !Sub "/${Product}/${Environment}/PDF_GENERATION_SQS_QUEUE"
      Type: String
      Value: !Ref PDFGenerationSQSQueue

  DeadLetterQueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm if DLQs contain messages"
      Namespace: "AWS/SQS"
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: RenderingSQSDeadLetterQueueName
          Value : !GetAtt RenderingSQSDeadLetterQueue.QueueName
        - Name: PDFGenerationSQSDeadLetterQueueName
          Value : !GetAtt PDFGenerationSQSDeadLetterQueue.QueueName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
