Transform: AWS::Serverless-2016-10-31

Parameters:
  Product:
    Description: Product name
    Type: String

  Environment:
    Description: An environment name that will be prefixed to resource names
    Type: String

Globals:
  Function:
    Runtime: ruby2.5
    Timeout: 60
    Handler: lambda.Lambda.handler
    Environment:
      Variables:
        S3_BUCKET: !Ref S3Bucket

Resources:
  RendererLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 'app/functions/renderer/'
      Environment:
        Variables:
          DOCUMENTS_SNS_TOPIC: !Ref DocumentsSNSTopic
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RendereingSQSQueue.Arn
            BatchSize: 1
      Layers:
        - !Ref RendererRubyGemsLayer
      Policies:
        - S3CrudPolicy:
          BucketName: !Ref S3Bucket
        - SQSPollerPolicy:
          QueueName: !GetAtt RendererSQSQueue.QueueName
        - SQSSendMessagePolicy:
          QueueName: !GetAtt PDFGenerationSQSQueue.QueueName

  RendererRubyGemsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: renderer
      ContentUri: .layers/renderer/
      CompatibleRuntimes:
        - ruby2.5
      RetentionPolicy: Delete

  PDFGeneratorLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 'app/functions/pdf_generator/'
      Environment:
        Variables:
          DOCUMENTS_SNS_TOPIC: !Ref DocumentsSNSTopic
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt PDFGenerationSQSQueue.Arn
            BatchSize: 1
      MemorySize: 512
      Layers:
        - arn:aws:lambda:ap-southeast-2:764866452798:layer:libreoffice:1
        - !Ref PDFGeneratorRubyGemsLayer
      Policies:
        - S3CrudPolicy:
          BucketName: !Ref S3Bucket
        - SQSPollerPolicy:
          QueueName: !GetAtt PDFGenerationSQSQueue.QueueName
        - SNSPublishMessagePolicy:
          TopicName: !GetAtt DocumentsSNSTopic.TopicName

  PDFGeneratorRubyGemsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pdf_generator
      ContentUri: .layers/pdf_generator/
      CompatibleRuntimes:
        - ruby2.5
      RetentionPolicy: Delete

  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub "${Product}-${Environment}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          -
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          -
            ExpirationInDays: 14
            Status: Enabled

  S3BucketSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description : "S3 Bucket"
      Name: !Sub "/${Product}/${Environment}/S3_BUCKET"
      Type: String
      Value: !Ref S3Bucket

  DocumentsSNSTopic:
    Type: AWS::SNS::Topic

  DocumentsSNSTopicSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description : "Documents SNS Topic"
      Name: !Sub "/${Product}/${Environment}/DOCUMENTS_SNS_TOPIC"
      Type: String
      Value: !Ref DocumentsSNSTopic

  RenderingSQSQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 360
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt RenderingSQSDeadLetterQueue.Arn
        maxReceiveCount: 3

  RenderingSQSDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600

  PDFGenerationSQSQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 360
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PDFGenerationSQSDeadLetterQueue.Arn
        maxReceiveCount: 3

  PDFGenerationSQSDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
